## 00.pytorch.PyTorch Fundamentals

> Indented block



Resource notebook:https://www.learnpytorch.io/00_pytorch_fundamentals/

If a question https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
print("Hello Im excited to learn pytorch")

Hello Im excited to learn pytorch


In [2]:
!nvidia-smi

Wed Sep 13 11:56:55 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## Intro to tensors

###creating tensors

PyTorch tensors are created using 'torch.Tensor()'-https://pytorch.org/docs/stable/tensors.html

In [23]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [24]:
scalar.ndim

0

In [25]:
#Get tensor back as Python int
scalar.item()

7

In [26]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [27]:
vector.ndim

1

In [28]:
vector.shape


torch.Size([2])

In [29]:
# matrix
MATRIX = torch.tensor([[7,8],
             [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [30]:
MATRIX.ndim

2

In [31]:
# FIRST DIMENSION
MATRIX[0]

tensor([7, 8])

In [32]:
MATRIX[1]

tensor([ 9, 10])

In [33]:
MATRIX.shape


torch.Size([2, 2])

In [34]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
            [3,4,5],
            [2,6,7]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [2, 6, 7]]])

In [35]:
TENSOR.ndim

3

In [36]:
# ONE 3BY3 TENSOR
# 第一个1 代表outer bracket，第二个数字3代表3个框住数字的框，第3个数字3代表一个最小框内的3个数字
TENSOR.shape

torch.Size([1, 3, 3])

In [37]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [2, 6, 7]])

In [40]:
TENSOR[1]

IndexError: ignored

In [41]:
TENSOR[2]

IndexError: ignored

#random tensors

Why random tensors?

Random tensors are important  because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

'Start with random numbers -> look at data -> update random numbers->look at data -> update random numbers'

Torch.random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [63]:
#create a random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0861, 0.0866, 0.6123, 0.5209],
        [0.1289, 0.6781, 0.0588, 0.0698],
        [0.8484, 0.9279, 0.7909, 0.0239]])

In [64]:
random_tensor.ndim

2

In [65]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # height,width, color channels (R, G, B)
random_image_size_tensor.shape,random_image_size_tensor.ndim
# torch.rand(3,4)=torch.rand(size=(3,4))

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [66]:
#create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [67]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [68]:
#create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [69]:
ones.dtype

torch.float32

In [70]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [71]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
#creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big issues/errors with PyTorch& Deep learning
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device

Precision in computing-
https://en.wikipedia.org/wiki/Precision_(computer_science)


In [73]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                dtype=None,# What datatype is the tensor,(e.g. float32 or float16)可以被定义为torch.float16等等；matter with precision in computing
                device="cuda",# What device is your tensor on
                requires_grad=False)# Whether or not to track gradients with this tensors operation
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [74]:
float_32_tensor.dtype

torch.float32

In [75]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor # check the tensor datatype

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [76]:
float_16_tensor*float_32_tensor#此处没有出现error，但其他dtype不match的情况可能会error

tensor([ 9., 36., 81.], device='cuda:0')

In [77]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)# no dots to make it float
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [78]:
float_32_tensor * int_32_tensor

RuntimeError: ignored

### Getting information from tensors (tensor attributes)

1. Tensor not right datatype - to get datatype from a tensor, can use'tensor.dtype'
2. Tensor not right shape - to get shape from a tensor, can use 'tensor.shape'
3. Tensor not on the right device - to get device from a tensor, can use 'tensor.device'

In [80]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3068, 0.1922, 0.1218, 0.3501],
        [0.5538, 0.7507, 0.4092, 0.9605],
        [0.9890, 0.0901, 0.6745, 0.1880]])

In [81]:
some_tensor.size, some_tensor.shape #attribute doesn't have a bracket

(<function Tensor.size>, torch.Size([3, 4]))

In [82]:
some_tensor.size

<function Tensor.size>

In [83]:
some_tensor.size() #function has its bracket behind

torch.Size([3, 4])

In [84]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.3068, 0.1922, 0.1218, 0.3501],
        [0.5538, 0.7507, 0.4092, 0.9605],
        [0.9890, 0.0901, 0.6745, 0.1880]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


from ast import Add
### Manipulating Tensors(tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix multiplication

In [85]:
# Create a tensor and add 1- to it
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [86]:
# Multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [87]:
tensor

tensor([1, 2, 3])

In [88]:
# Subtract 10
tensor-10

tensor([-9, -8, -7])

In [89]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [90]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networkd and deep learning

1. Element-wise multiplication
2. Matrix multiplication(dot product)

More information on multiplying matrixes-
https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are 2 main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* only'(3,2)@(2,3)'will work but not (3,2)@(3,2)
2. The resulting matrix has the shape of the **outing dimensions**:
* '(2,3)*(3,2)'->'(2,2)'
* '(3,2)*(2,3)'->'(3,2)'

In [91]:
torch.rand(3,2).shape

torch.Size([3, 2])

In [92]:
# Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [93]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [94]:
tensor @tensor

tensor(14)

In [95]:
tensor

tensor([1, 2, 3])

In [96]:
#matrix multiplication by hand
1*1+2*2+3*3

14

In [97]:
%%time
value=0
for i in range(len(tensor)):
 value +=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 0 ns, sys: 352 µs, total: 352 µs
Wall time: 361 µs


In [98]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 28 µs, sys: 5 µs, total: 33 µs
Wall time: 35.8 µs


tensor(14)

### One of the most common errors in deep learning:shape errors

check:http://matrixmultiplication.xyz/


In [99]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
              [3,4],
              [5,6]])
tensor_B = torch.tensor([[7,10],
              [8,11],
              [9,12]])

# torch.matmul = torch.mm
torch.mm(tensor_A,tensor_B)


RuntimeError: ignored

In [101]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix the tensor shape issues, we can manipulate the shape of one of our tensors using **teanspose**

A **transpose** switches the axes or dimensions of a given tensor

In [102]:
tensor_B.T,tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [103]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [104]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [105]:
torch.mm(tensor_A,tensor_B.T).shape

torch.Size([3, 3])

In [106]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A ={tensor_A.shape}, tensor_B ={tensor_B.shape}")
print(f"New shapes: tensor_A ={tensor_A.shape}(same shape as above),tensor_B.T ={tensor_B.T.shape}")
print(f"Multiplying:{tensor_A.shape}@{tensor_B.shape}<- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape:{output.shape}")

Original shapes: tensor_A =torch.Size([3, 2]), tensor_B =torch.Size([3, 2])
New shapes: tensor_A =torch.Size([3, 2])(same shape as above),tensor_B.T =torch.Size([2, 3])
Multiplying:torch.Size([3, 2])@torch.Size([3, 2])<- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape:torch.Size([3, 3])


## Finding the min, max,mean, sum, etc (tensor aggregation)

In [107]:
# Create a tensor
x = torch.arange(1,100,10)
x,x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [108]:
# Find the min
torch.min(x),x.min()

(tensor(1), tensor(1))

In [109]:
# Find the max
torch.max(x),x.max()

(tensor(91), tensor(91))

In [110]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)),x.type(torch.float).mean()

(tensor(46.), tensor(46.))

In [111]:
# Find the sum
torch.sum(x),x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [112]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [113]:
x[0]

tensor(1)

In [114]:
#  the position of maximum value
x.argmax()

tensor(9)

In [115]:
x[9]

tensor(91)

In [116]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other(vstack) or side by side (hstack)
* Squeeze - removes all "1" dimensions from a tensor
* Unsqueeze - add a "1" dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [117]:
# Create a tensor
import torch
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [118]:
# Add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [119]:
# Change the view
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [120]:
# Changing z changes x(because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [121]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [122]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [123]:
# Note:vstack using dimension=0,hstack using dimension=1

In [124]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor:{z}")
print(f"Previous shape:{x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
z_squeezed = z.squeeze()
print(f"\nNew tensor:{z_squeezed}")
print(f"New shape:{z_squeezed.shape}")

Previous tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape:torch.Size([9, 1])

New tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape:torch.Size([9])


In [125]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target:{z_squeezed}")
print(f"Previous shape:{z_squeezed.shape}")

# Add an extra dimension with unsqueeze
z_unsqueezed = z_squeezed.unsqueeze(dim=0)#could be 1 or any number
print(f"\nNew tensor:{z_unsqueezed}")
print(f"New shape:{z_unsqueezed.shape}")

Previous target:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape:torch.Size([9])

New tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape:torch.Size([1, 9])


In [126]:
# torch.permute - rearrange the dimensions of a target tensor in a specified order
x_original = torch.rand(size = (224,224,3)) #[height,width,colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) #shifts axis 0->1,1->2,2->0

print(f"Previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}") #[colour_channels,height,width]

Previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


In [127]:
x_original[0,:,:]

tensor([[1.7089e-01, 1.7632e-02, 4.3481e-02],
        [6.0381e-01, 4.2526e-01, 7.4685e-01],
        [3.4376e-01, 9.8436e-01, 7.0493e-01],
        [3.1998e-01, 5.5002e-01, 7.9133e-01],
        [3.1180e-01, 2.8556e-01, 5.8979e-01],
        [5.5454e-01, 5.3875e-01, 1.0232e-01],
        [9.4345e-01, 5.7106e-01, 5.1514e-01],
        [4.3002e-01, 9.2089e-01, 4.0737e-01],
        [7.7832e-01, 5.1747e-01, 7.2490e-01],
        [7.2091e-01, 2.5174e-01, 2.9850e-01],
        [3.1354e-01, 8.3197e-01, 5.0670e-01],
        [6.4628e-01, 6.1583e-01, 4.6253e-01],
        [2.8256e-01, 6.7452e-01, 2.6918e-01],
        [8.8058e-01, 9.5841e-03, 5.7448e-01],
        [9.5862e-01, 6.8538e-01, 1.7251e-01],
        [7.8655e-02, 4.7213e-01, 8.1071e-01],
        [4.0672e-01, 2.1577e-01, 6.2870e-01],
        [1.5259e-01, 3.7300e-01, 6.8645e-01],
        [9.1034e-01, 5.5159e-01, 1.4310e-02],
        [1.2809e-01, 6.8071e-01, 4.8352e-01],
        [6.5018e-01, 7.2747e-01, 4.6164e-01],
        [9.5220e-01, 2.2907e-01, 7

In [128]:
x_original[0,0,0] =728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with Numpy.

In [129]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3) #从1开始到10-1=9
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [130]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [131]:
# Let's index on the middle bracket(dim=1)
x[0][0] # whose effect is the same as x[0,0]

tensor([1, 2, 3])

In [132]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]
x[0][1][1]

tensor(5)

In [133]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [134]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]
# result would be tensor([[2, 5, 8]])

tensor([[2, 5, 8]])

In [135]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1] # result:tensor([5])
#comparison: x[0,1,1] result:tensor(5)

tensor([5])

In [136]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:] #result:tensor([1, 2, 3])
#comparison x[0][0],result:tensor([1, 2, 3])

tensor([1, 2, 3])

In [137]:
# Index on x to return 9
# Index on x to return 3,6,9
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [138]:
x[:,2,2] #result:tensor([9])

tensor([9])

In [139]:
x[0,2,2] #result:tensor(9)

tensor(9)

In [140]:
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> 'torch.from_numpy(ndarray)'
* PyTorch tensor -> NumPy ->'torch.Tensor.numpy()'

In [141]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor
#result would be (array([1., 2., 3., 4., 5., 6., 7.]),
# tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [142]:
array.dtype

dtype('float64')

In [143]:
torch.arange(1.0, 8.0).dtype
# result:torch.float32

torch.float32

In [144]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32) #dtype=torch.float32 wouldn't work out
# warning: when converting from numpy ->pytorch,pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [145]:
tensor.dtype

torch.float32

In [146]:
# Change the value of array, what will this do to "tensor"?
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [147]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [148]:
numpy_tensor.dtype
# default of a pytorch tensor datatype is float 32,so when a tensor converts to numpy array, its dtype is also float32
# default datatype of a numpy array is float 64, when an array converts to a pytorch tensor, its datatype is also float64

dtype('float32')

In [150]:
# Change the tensor, what happens to 'numpy_tensor'
tensor = tensor+1
  tensor, numpy_tensor
# result would be (tensor([2., 2., 2., 2., 2., 2., 2.]),
# array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

IndentationError: ignored

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

‘start with random numbers -> tensor operations-> update random numbers to try and make them better representations of the data -> again->again->again->...’

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness.

In [152]:
import torch

# Create 2 random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2650, 0.2812, 0.6217, 0.4728],
        [0.0605, 0.3347, 0.3585, 0.5351],
        [0.1758, 0.5767, 0.5170, 0.4105]])
tensor([[0.4326, 0.5325, 0.9968, 0.3762],
        [0.8263, 0.5737, 0.9827, 0.6441],
        [0.5161, 0.5771, 0.0496, 0.3437]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [154]:
1 ==1

True

In [158]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)# 注意，不加这一句，会是不同tensor
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility

*https://pytorch.org/docs/stable/notes/randomness.html

*https://en.wikipedia.org/wiki/Random_seed

##Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everthing hunky dory(good).

### 1. Getting a GPU
1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit og setup and requires the investment of purchasing a GPU, there's lots of options..., see this post for what option to get :https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning:https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services aloow you to rent computers on the cloud and access them

For2,3 PyTorch + GPU drivers(CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/cloud-partners/

In [4]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


###2. Check for GPU access with PyTorch

In [9]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

For PyTorch since it's capable of running compute on the GPU or CPU,it's best practice to setup device agnostic code:https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available, else default to CPU

In [4]:
# Setup device agnostic code
device ="cuda" if torch.cuda.is_available()else"cpu"
device

'cuda'

In [5]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors(and models) on the GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [6]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3],device ="cpu" )#后半句不加上，则默认在cpu

#Tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
#Move tensor to GPU(if available)
tensor_on_gpu=tensor.to(device)# keep to device in mind
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [8]:
# If tensor is on GPU, can't transform it to NumPy # 3种大error：shape；datatype；device issues

tensor_on_gpu.numpy()

TypeError: ignored

In [10]:
# To fix the GPU tensor with Numpy issue, we ca first set it to the CPU
tensor_back_on_cpu= tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu


array([1, 2, 3])

In [12]:
tensor_on_gpu


tensor([1, 2, 3], device='cuda:0')

## Exercises & Extra-curriculum

See exercises for this notebook here:https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises